name: need_customer
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4+24

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.2
  # fancy_bottom_navigation: ^0.3.2
  firebase_core: ^0.4.0
  geolocator: ^5.3.0
  geocoder: ^0.2.1
  awesome_dialog: ^0.1.3
  flip_card: ^0.4.4
  cloud_firestore: ^0.13.4+2
  permission_handler: ^5.0.0+hotfix.3
  geoflutterfire: ^2.1.0
  firebase_auth: ^0.16.0
  google_sign_in: ^4.1.4
  connectivity: ^0.4.8+2
  google_maps_flutter: ^0.5.26+4
  flutter_google_places: ^0.2.4
  google_maps_webservice: ^0.0.16
  flutter_money_formatter: ^0.8.3
  sliding_up_panel: ^1.0.2
  flutter_launcher_icons: ^0.7.5
  firebase_messaging: ^6.0.16
  carousel_slider: ^2.1.0
  url_launcher: ^5.4.10
  # persistent_bottom_nav_bar: ^1.5.5
  flutter_open_whatsapp: ^0.1.2
  flutter_rating_bar: ^3.0.1+1
  cached_network_image: ^2.2.0+1
  flutter_cache_manager: ^1.4.1
  dotted_border: ^1.0.5
  intl: ^0.15.8
  firebase_analytics: ^5.0.16
  ntp: ^1.0.7
  percent_indicator: ^2.1.5
  # background_fetch: ^0.6.0
  image_picker: ^0.6.7+7
  firebase_storage: ^3.1.5
  flutter_image_compress: ^0.7.0
  location: ^3.2.4
  flutter_polyline_points: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo3.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/aqua.png
    - assets/images/vit.png
    - assets/images/club.png
    - assets/images/cleo.png
    - assets/images/galon.png
    - assets/images/pasar.png
    - assets/images/menual.png
    - assets/images/menuro.png
    - assets/images/menuuf.png
    - assets/images/marker.png
    # - assets/images/lainnya.png
    - assets/images/pattern.jpg
    - assets/images/note_taking.png
    - assets/images/order_confirmed.png
    - assets/images/batalkan2.png
    - assets/images/laundry.jpeg
    - assets/images/googlemapsicon.png
    # - assets/images/glon.jpg
    - assets/images/brand.jpg
    - assets/images/pattern2.png
    - assets/images/notifications.png
    - assets/images/gallon.jpg
    - assets/images/user.png
    - assets/images/loading.gif
    - assets/images/dibatalkan.png
    - assets/images/dalam_proses.png
    - assets/images/pengantaran.png
    - assets/images/telahselesai.png
    - assets/images/googleloginlogo.png
    - assets/images/city.png
    - assets/logo/logo3.png
    - assets/logo/logo2.png
    - assets/logo/logo4.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Anton-Regular
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Monoton-Regular
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf
    - family: BerkshireSwash-Regular
      fonts:
        - asset: assets/fonts/BerkshireSwash-Regular.ttf
    - family: CabinSketch-Regular
      fonts:
        - asset: assets/fonts/CabinSketch-Regular.ttf
    - family: CinzelDecorative-Regular
      fonts:
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
